### POST CUSTOMER
POST http://localhost:8080/customers
Accept: */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{"firstName":"John","lastName":"Doe"}


### PUT CUSTOMER
PUT http://localhost:8080/customers/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8

{"id": 3, "firstName":"Jane","lastName":"Doe"}

### DELETE CUSTOMER
DELETE http://localhost:8080/customers/3
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8


### GET ALL CUSTOMERS
GET http://localhost:8080/customers
Accept: */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache


### GET ONE CUSTOMER
GET http://localhost:8080/customers/1
Accept: */*
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache







### Login
POST https://kotlin-spring-boot.auth0.com/oauth/token
Content-Type: application/json

{
"client_id":"xPHJ6na0YwJjHvpzcwAMojbyagIF3OnB",
"client_secret":"lPzHUf1GF4lsZSkg2APSTZAKt-MjOiC6QssFwIdmiv_oU9PXE0aqalj90jHK2PzD",
"audience":"kotlin-jwt",
"grant_type":"client_credentials"
}

### Get Secure API
GET http://localhost:8080/customers/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlEwWXhPVU0wUmtNME5EWkZNVGd5T0RBNU5VTkNNelV3UVVJeFFUVkJOVVF4TTBKRFFUUkdOdyJ9.eyJpc3MiOiJodHRwczovL2tvdGxpbi1zcHJpbmctYm9vdC5hdXRoMC5jb20vIiwic3ViIjoieFBISjZuYTBZd0pqSHZwemN3QU1vamJ5YWdJRjNPbkJAY2xpZW50cyIsImF1ZCI6ImtvdGxpbi1qd3QiLCJpYXQiOjE1MjMxNjc1NjksImV4cCI6MTUyMzI1Mzk2OSwiYXpwIjoieFBISjZuYTBZd0pqSHZwemN3QU1vamJ5YWdJRjNPbkIiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.erz4ec3R2FYCP5TmiI5bZBlkBCS774t34k00lekyD2zhropY2Ay2SY2zJ6TtSyIS805eh4F0P4tLoQ_0r4H3HwfM-kNGui7OuIzPiusFb63wYrI_4gsY8BiJ018zWFFdi3A0bcWBVD5gCtOhjlVhBu-nECxDnnqArVZM1DcHazsUTWjyuu1-hTUtWK5EIWOopn-snORwKAFjJb8NyDuQa5pvvliQG9dsI_7VcR558IaoCYLgcoLaq-nbu72b3DmfAfCAqEi-XVIfxRlKtGhwog4mU7eXFUL0xHWg7029kxgm4NXGmsnqeP7c9-5Ygo2manHM4vKhrWoETHg1iJg_uQ






